name = "claude-vision-api"
main = "src/index.js"
compatibility_date = "2024-01-01"

[env.production.vars]
# These will be set via wrangler secret put
# ANTHROPIC_API_KEY = "your-api-key"
# ALLOWED_ORIGINS = "https://yourdomain.com,https://anotherdomain.com"

[[env.production.kv_namespaces]]
binding = "SESSIONS"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"

[limits]
cpu_ms = 10000